### ISSUE TITLE
Switch authentication method to API tokens

### ISSUE THREAD

**Issue by neomilium** [fog/fog-proxmox#63]
As experienced and seen in [foreman fog proxmox issues](https://github.com/theforeman/foreman_fog_proxmox/issues), authentications against Proxmox raise many troubles.

From developer point of view, the current authentication method could be a puzzle: using user+password, then user+ticket and ensure ticket is renewed at right time, etc.

Fortunately, Proxmox adds _API tokens_ feature in [6.2](https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_6.2) which should reduce authentication troubles.

[Here a link to documentation about API tokens from Proxmox](https://pve.proxmox.com/pve-docs/chapter-pveum.html#pveum_tokens)

What do you thing about switching to _API tokens_, which seems to be designed to do exactly what we want to?

**Comment by tristanrobert** [comment]
These tokens have a lifetime too. It is different from the one required: https://pve.proxmox.com/wiki/Proxmox_VE_API. I don't know which one is required by proxmox now. It is not clear. It is a big change. It needs tests in the plugin and more documentation from Proxmox.

**Comment by neomilium** [comment]
AFAICS, the proxmox documentation you mention is for the _ticket_ system you already implemented. I did not find a documentation section that explains the new feature.
Nevertheless, I agree its not clear and is a big change, for the best, isn't it?

So, OK if you want to wait for a better documentation from _Proxmox_.

**Comment by tristanrobert** [comment]
I have test it. It could be added in a major version but it will work only with Proxmox >= 6.2. So users should take this new major version to have this new feature unless they have to you use previous ones. I don't recommend to maintain the two ways of API authentication: the old and the new one. It may add too much complexity and thus it could weaken the code.

**Comment by tristanrobert** [comment]
This new way of authentication is much better: stateless, more secure (limited privileges), etc. I agree it is a far better way to authenticate and it should fix some issues.

**Comment by wech71** [comment]
I also regularly experience the problems with the expired proxmox api tokens.

The new API tokens description is here https://pve.proxmox.com/pve-docs/chapter-pveum.html#pveum_tokens as neomilium already mentioned.

These API tokens don't have to be renewed. There is no api ticket which has to be acquired first (as being described in the "classic" username+password api-ticket request system https://pve.proxmox.com/wiki/Proxmox_VE_API).

The api can just be used with an API token.

I used them recently to get the live charts for external charting all running VMs. Its much easier than having to obtain a temporary token first and having to remember to renew it regularly. Also there is no CSRF token which has to be maintained over modifying calls.

So it is perfect for scripted automation like the use case in foreman.

Instead of an username and password, the api request has only to set an "Authorization" header with an value in the format "PVEAPIToken=grantusername@pve!tokenname=apitokensecret"

"grantusername " being e.g. "root" (the user for which the api token is being issued)
"apitokensecret" is the secret being displayed when creating the api user token.

The main complication in my opinion is how to allow for updates from current version when switching to api tokens as users will have to create api tokens by hand and enter the new credentials. Maybe it would be good to provide an option to switch between username/password and token based authentication.

**Comment by neomilium** [comment]
@wech71 Thanks for explanations and experience feedback.

About the upgrade path, from my point of view, we should simply drop the current auth mecanism totally and implement a simple API token and warn user about the breaking change in changelog.
Its really simple to grab a new API token from Proxmox and copy/paste credentials into Foreman will increase the maintenance work made by @tristanrobert (Thanks to him! BTW).

API token is the future for Proxmox, it should be for fog-proxmox.
